name: food_diary
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 1.13.1
  velocity_x: 3.4.0
  get: 4.6.1
  get_storage: 2.0.3
  firebase_auth: 3.3.9
  google_sign_in: 5.2.4
  http: 0.13.4
  cloud_firestore: 3.1.10
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

get_cli: 
  separator: .
  sub_folder: false

